### ISSUE TITLE
Very good job, but i want to know whether “GradientAscent” can visualize ResNet?

### ISSUE THREAD

**Issue by XKMar** [MisaOgura/flashtorch#10]

**Comment by MisaOgura** [comment]
Thanks @XKMar,

And yes, `GradientAscent` works with ResNet.

For the models that doesn't come with `features`/`classifier` separation, please pass in the _whole model_ when you create an instance.

Then find a conv layer of your interest and specify it when invoking `visualize` method.

Hope below snippet helps:
<img width="1059" alt="Screen Shot 2019-09-19 at 14 17 09" src="https://user-images.githubusercontent.com/16384171/65247591-8b8c3400-dae8-11e9-95e4-9272f40b066b.png">

Please reopen this issue if this doesn't answer your question.

Many thanks,
Misa
