### ISSUE TITLE
[REQUEST]hello, i have a suggestions. "g_scent.visualize" only work on the jupter notebook etc, some platform not suggest visualize, so i think the figure can be save on Local directory？

### ISSUE THREAD

**Issue by XKMar** [MisaOgura/flashtorch#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MisaOgura** [comment]
Hi @XKMar 

Thanks for the suggestion, and I think it's a great idea.

I would appreciate if you could:

- give the issue a concise title
- fill out the questions in the template, with as much detail as you can give to explain how you envision this feature

If you don't have detailed specifications yet, please close the issue.

I'm happy to discuss further on the [Gitter community channel](https://gitter.im/flashtorch/community).

Many thanks,
Misa
