### ISSUE TITLE
[BUG]UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 5424: illegal multibyte sequence

### ISSUE THREAD

**Issue by huaji0353** [MisaOgura/flashtorch#14]
**Describe the bug**
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HUAJI0~1\AppData\Local\Temp\pip-install-uc9zsivx\flashtorch\setup.py", line 5, in <module>
        long_description = fh.read()

UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 5424: illegal multibyte sequence

**To Reproduce**
pip install flashtorch

**Environment (please complete the following information):**
 - OS: windows10
 - Python version: 3.7
 - FlashTorch version: 0.1.0

**fix**
readme.md line 101
 “see” fix to "see"

**Comment by MisaOgura** [comment]
Hi @huaji0353 

Thanks for the bug report.

I think it would be probably better to remove the dependency on the `README`, so this doesn't happen again.

The fix will come shortly.

Many thanks,
Misa

**Comment by MisaOgura** [comment]
Hi @huaji0353 

I've released a fix as a version `0.1.1`.

Can you try to install this version, and let me know if the bug has been fixed?

Many thanks,
Misa

**Comment by huaji0353** [comment]
Successfully installed flashtorch-0.1.1

it work！

**Comment by huaji0353** [comment]
Successfully installed flashtorch-0.1.1

it work！
