### ISSUE TITLE
backprop.visualize does not display anything

### ISSUE THREAD

**Issue by goldblum** [MisaOgura/flashtorch#17]
I followed the tutorial on the README page, and the visualizations are not displaying.  I am using a pretrained model, and I use a tensor with requires_grad=True as the image.  My code doesn't run in to any errors.  My code is below:

backprop = Backprop(net)
backprop.visualize(image, target_class, guided = True)

**Comment by MisaOgura** [comment]
Hi @goldblum,

Thanks for raising an issue.

Could you provide some more information as to how you are using FlashTorch?

For example:
 - OS: [e.g. iOS]
 - Python version: [e.g. 3.6]
 - Jupyter Notebook version: [e.g. 6.0.1]
 - FlashTorch version: [e.g. 0.1.0]
 - Model architecture: [e.g. VGG16]

And any other information you think would be relevant with your issue.

Many thanks,
Misa

**Comment by jstagliano30** [comment]
I had the same issue. I fixed it by importing matplotlib.pyplot and after the backprop.visualize function putting in the show function. My code is below the versions text.

The software versions I use are:
OS: Ubuntu 18.04 LTS
Python 3.7.5
Jupyter Notebook (do not use) 
FlashTorch: 0.1.1
Model Architecture: Alexnet

import matplotlib.pyplot as plt
import torchvision.models as models
from flashtorch.utils import apply_transforms
from flashtorch.utils import load_image
from flashtorch.saliency import Backprop

model = models.alexnet(pretrained=True)
backprop = Backprop(model)
image = load_image('../examples/images/great_grey_owl.jpg')
input_ = apply_transforms(image)
target_class = 24
backprop.visualize(input_,target_class,guided=True)
plt.show() # needed  for the plot to show

**Comment by navneeth** [comment]
Indeed as pointed out by @jstagliano30 the call to `plt.show()` should solve your issue.
```
backprop = Backprop(net)
backprop.visualize(image, target_class, guided = True)
put.show()
```

**Comment by MisaOgura** [comment]
Thanks @jstagliano30 @navneeth for jumping in.

An alternative is to enable inline plotting for the whole notebook by putting `%matplotlib inline` **before** importing `matplotlib`, as explained [here](https://stackoverflow.com/a/24884342) for example. This will help avoid calling `plt.show()` multiple times.
