### ISSUE TITLE
Calculate Gradient function does not take in the use_gpu flag

### ISSUE THREAD

**Issue by vinayshekharcmu** [MisaOgura/flashtorch#18]
Calculate Gradient function does not take in the use_gpu flag. Although the flag is taken in the visualize function, it is not used in the calculate_graidents function

**Comment by vinayshekharcmu** [comment]
I have a PR ready. But don't have permission to push to the repo.

**Comment by MisaOgura** [comment]
Hi @vinayshekharcmu,

Thank you for your suggestion.

Indeed, this is something I intend to work on to unify the interface between the modules.

If you'd like to discuss your implementation, please feel free to open a Pull Request.

Many thanks,
Misa
