### ISSUE TITLE
[BUG] Backprop.calculate_gradients gives rise to " AttributeError: 'NoneType' object has no attribute 'shape' " error

### ISSUE THREAD

**Issue by narbhar** [MisaOgura/flashtorch#23]
**Describe the bug**
When testing the visualization tool using a custom pre-trained CNN that performs Binary Classification, the error "AttributeError: 'NoneType' object has no attribute 'shape'" crops up when trying to visualize an image that from the dataset used to train the model. 

**To Reproduce**
Load image using custom transformation:
`transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])
`
 that pertains to the CNN model developed.
Load the image and apply the transformation:
`from flashtorch.utils import load_image`
`from flashtorch.saliency import Backprop`
`backprop=Backprop(n)`
`image =load_image("img0042.png")`
`i = transform(image)`
`i = torch.unsqueeze(i,0)`
`target_class=0`
`gradients=backprop.calculate_gradients(i,0)`
(general summary of the code)

**Error message**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-18e9aeeac78d> in <module>
      1 from torch.autograd import Variable
----> 2 gradients=backprop.calculate_gradients(i,0)

~\Anaconda3\lib\site-packages\flashtorch\saliency\backprop.py in calculate_gradients(self, input_, target_class, take_max, guided, use_gpu)
    118         # Calculate gradients of the target class output w.r.t. input_
    119 
--> 120         output.backward(gradient=target)
    121 
    122         # Detach the gradients from the graph and move to cpu

~\Anaconda3\lib\site-packages\torch\tensor.py in backward(self, gradient, retain_graph, create_graph)
    164                 products. Defaults to ``False``.
    165         """
--> 166         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    167 
    168     def register_hook(self, hook):

~\Anaconda3\lib\site-packages\torch\autograd\__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     97     Variable._execution_engine.run_backward(
     98         tensors, grad_tensors, retain_graph, create_graph,
---> 99         allow_unreachable=True)  # allow_unreachable flag
    100 
    101 

~\Anaconda3\lib\site-packages\flashtorch\saliency\backprop.py in _record_gradients(module, grad_in, grad_out)
    212     def _register_conv_hook(self):
    213         def _record_gradients(module, grad_in, grad_out):
--> 214             if self.gradients.shape == grad_in[0].shape:
    215                 self.gradients = grad_in[0]
    216 

AttributeError: 'NoneType' object has no attribute 'shape'

**Environment (please complete the following information):**
 - OS: [Windows 10 1909 version: 18363.476]
 - Python version: [3.7..4]
 - FlashTorch version: [0.1.1]

**Comment by lustea0201** [comment]
Have you been able to solve this ?

**Comment by MisaOgura** [comment]
Thanks @lustea0201, @narbhar apologies for the lateness of this reply. If you still experience this problem after setting `requires_grad` to `True` on the input tensor, please reopen this issue.

**Comment by francescogianferraripini** [comment]
Hi, I face the same problem, using the flashtorch load_image method.
Therefore requires_grad is already set to true.
I am using a resnet18 on binary classification.
