### ISSUE TITLE
How can I use FlashTorch to see what the EfficientNet learn?

### ISSUE THREAD

**Issue by ChenXiao61** [MisaOgura/flashtorch#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python version: [e.g. 3.6]
 - FlashTorch version: [e.g. 0.1.0]

**Additional context**

**Comment by MisaOgura** [comment]
@ChenXiao61 The pre-trained EfficientNet models are available from https://github.com/lukemelas/EfficientNet-PyTorch#loading-pretrained-models

Once you install the package and follow the instruction to load a model, you should be able to use it with the `Backprop` class to create saliency maps like any other models loaded from torchvision.models.
