### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by surajpaib** [MisaOgura/flashtorch#30]
**Problem Faced:**
Backprop visualize doesn't consider models with grayscale input. 

**Description:**
Refer to this line:
https://github.com/MisaOgura/flashtorch/blob/ba5e3db3911afee583180bead9150ce4c392e09e/flashtorch/saliency/backprop.py#L222
In this line we add a check for 3 channels which results in skipping grayscale inputs to the conv layer

**My current workaround:**
I have a copy of the backprop class with the in_channels set to 1 for my grayscale image use case. 

**Possible Fix:**
Would it make sense to remove the in_channels == 3 check since the first conv would be where the input image is supplied and should be good to register the hook at or am I missing something important here?

**Comment by MisaOgura** [comment]
Hi @surajpaib, thanks for the request!

Accommodating for models that handle greyscale input images definitely makes sense in terms of improving the versatility of the tool.

I have opened a PR for this: #31

**Comment by MisaOgura** [comment]
Hi @surajpaib,

The latest version 0.1.3 implements this improvement.

It would be great if you could use this version and see if it provides the functionality you require.

Many thanks!

**Comment by surajpaib** [comment]
@MisaOgura Perfect! Will test it over the weekend and report my findings, if any! Thanks
