### ISSUE TITLE
Can I use my own model?

### ISSUE THREAD

**Issue by zxupstar** [MisaOgura/flashtorch#32]
If so, are there any requirements for the model?

**Comment by MisaOgura** [comment]
Hi @zxupstar,

FlashTorch is fairly agnostic to various model architectures.

For creating saliency maps, your model needs to have at least one conv2d layer as it will find the first conv2d layer and grabs gradients from it.

For activation maximisation, you have the control to specify which layers/filters to visualise.

Let me know if you encounter any problems.

**Comment by SarfarazHabib** [comment]
Hi @MisaOgura I am having problems using activation maximization on my own model. Have mentioned the details in a new issue. Can you please have a look ?

**Comment by MisaOgura** [comment]
I'm closing this for now - @zxupstar please re-open this if/when needed.

Thanks @SarfarazHabib I will reply on the thread in #34
