### ISSUE TITLE
User API Guide

### ISSUE THREAD

**Issue by InstantWindy** [MisaOgura/flashtorch#4]
Hi ! Is the user API guide of the flashtorch toolkit available? For the first time, I don't know which modules and functions are there. Thanks.

**Comment by MisaOgura** [comment]
Hey @InstantWindy,

I haven't got around to build a proper API guide just yet, but it's definitely on my mind & to-do list :)

As a quick workaround, I've included output of `help` function in the [Quick API Guide](https://github.com/MisaOgura/flashtorch/wiki/Quick-API-Guide) wiki page, which is also reference in [README](https://github.com/MisaOgura/flashtorch#api-guide).

Hope this helps!
